---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/npbahrmy/public_html/
    - /usr/bin/rsync -av --delete --exclude='.git' --exclude='.cpanel.yml' ./ $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - /bin/chmod 644 $DEPLOYPATH/.htaccess